name: IridiumSkyblock
version: 2.6.5
description: Skyblock Redefined
main: com.iridium.iridiumskyblock.IridiumSkyblock
api-version: '1.13'
author: IridiumDevelopment
load: STARTUP
depend: [ Vault ]
softdepend: [ RoseStacker, WorldEdit, PlaceholderAPI, MVdWPlaceholderAPI, WildStacker, EpicSpawners, UltimateStacker, MergedSpawner, Vault, Multiverse-Core, Essentials, EssentialsChat, ChatManager, DeluxeChat ]
commands:
  island:
    aliases: [ "is", "IridiumSkyblock" ]
    description: Main plugin command